//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAnim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatasContainer : DbContext
    {
        public DatasContainer()
            : base("name=DatasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prestation> Prestation { get; set; }
        public virtual DbSet<TypePrestation> TypePrestation { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Lieu> Lieu { get; set; }
        public virtual DbSet<Devis> Devis { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<DevisArticle> DevisArticle { get; set; }
    }
}
