//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAnim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevisArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevisArticle()
        {
            this.Devis = new HashSet<Devis>();
        }
    
        public int Id { get; set; }
        public string Quantite { get; set; }
        public string Description { get; set; }
        public string PrixUnitaire { get; set; }
    
        public virtual Unite Unite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devis> Devis { get; set; }
        public virtual Article Article { get; set; }
    }
}
