//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAnim.Models
{
    using System;
    
    public enum E_FactureStatus : int
    {
        DEVIS_BROUILLON = 1,
        DEVIS_ENVOYE = 2,
        DEVIS_SIGNE = 4,
        DEVIS_REFFUSE = 8,
        FACTURE_ENVOYE = 16,
        FACTURE_PAYE = 32
    }
}
