//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAnim.Models
{
    using System;
    
    public enum E_PrestationEtat : int
    {
        PREMIER_CONTACT = 1,
        DEVIS_ENVOYE = 2,
        DEVIS_SIGNE = 4,
        RDV_PRIS = 8,
        CONTRACT_SIGNE = 16,
        CHEQUE_CAUTION_REMIS = 32,
        PRESTATION_PAYE = 64,
        ANNULE = 128
    }
}
