//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAnim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestation()
        {
            this.Prestataires = new HashSet<Prestataire>();
            this.PrestationContact = new HashSet<PrestationContact>();
            this.Clients = new HashSet<Client>();
            this.Devis = new HashSet<Devis>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> HoraireDebut { get; set; }
        public Nullable<System.DateTime> HoraireFin { get; set; }
        public E_PrestationEtat Etat { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestataire> Prestataires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestationContact> PrestationContact { get; set; }
        public virtual Lieu Lieu { get; set; }
        public virtual TypePrestation TypePrestation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devis> Devis { get; set; }
        public virtual Facture Facture { get; set; }
    }
}
